service: drone-delivery

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DATABASE_PATH: './database.sqlite'

plugins:
  - serverless-offline

functions:
  registerDrone:
    handler: handlers/drone.registerDrone
    events:
      - http:
          path: drones/register
          method: post

  getDrones:
    handler: handlers/drone.getDrones
    events:
      - http:
          path: drones
          method: get

  updateDroneState:
    handler: handlers/drone.manageDroneState
    events:
      - http:
          path: drones/state
          method: post

  loadMedication:
    handler: handlers/medication.loadMedication
    events:
      - http:
          path: drones/load
          method: post

  getBatteryLogs:
    handler: handlers/logs.getBatteryLogs
    events:
      - http:
          path: logs/battery
          method: get

  drainBattery:
    handler: handlers/batteryDrain.drainBattery
    timeout: 15
    events:
      - schedule:
          rate: rate(1 minute)

  generateReport:
    handler: handlers/report.generateReport
    timeout: 15
    events:
      - http:
          path: report
          method: get
          request:
            parameters:
              querystrings:
                startDate: false
                endDate: false

